# Generated by Django 4.2.4 on 2023-09-04 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('carer', models.CharField(max_length=200)),
                ('semester', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surnames', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('career', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.CharField(max_length=200)),
                ('datetimelimit', models.DateTimeField(verbose_name='date published')),
                ('points', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_teacher', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='files/%Y/%m/%d/')),
                ('qualification', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.task')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_student', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('student_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.student_task')),
            ],
        ),
    ]
